import type { FilterAction, FilterRule, FilterSection, RuleCondition, SimulationItem } from "../types";

const quote = (value: string) => `"${value.replace(/"/g, '\\"')}"`;

function renderValues(values: string[]) {
  return values.map(quote).join(" ");
}

export function renderCondition(condition: RuleCondition): string {
  if ("operator" in condition && "values" in condition && condition.operator) {
    return `${condition.keyword} ${condition.operator} ${renderValues(condition.values)}`;
  }
  if ("values" in condition) {
    return `${condition.keyword} ${renderValues(condition.values)}`;
  }
  if ("operator" in condition && "value" in condition && typeof condition.value === "number") {
    const op = condition.operator === "=" ? "" : ` ${condition.operator}`;
    return `${condition.keyword}${op} ${condition.value}`;
  }
  return `${condition.keyword} ${condition.value ? "True" : "False"}`;
}

export function renderAction(action: FilterAction): string {
  switch (action.keyword) {
    case "SetFontSize":
      return `SetFontSize ${action.value}`;
    case "SetTextColor":
    case "SetBorderColor":
    case "SetBackgroundColor":
      return `${action.keyword} ${action.value.r} ${action.value.g} ${action.value.b} ${action.value.a}`;
    case "PlayAlertSound":
      return `PlayAlertSound ${action.id} ${action.volume}`;
    case "PlayEffect":
      return `PlayEffect ${action.color}${action.temp ? " Temp" : ""}`;
    case "MinimapIcon":
      return `MinimapIcon ${action.size} ${action.color} ${action.shape}`;
    case "DisableDropSound":
      return `DisableDropSound ${action.value ? "True" : "False"}`;
  }
}

export function renderRule(rule: FilterRule): string {
  if (!rule.enabled) return "";
  const header = `${rule.directive}${rule.tierTag ? ` # ${rule.tierTag}` : ""}`;
  const body = [
    ...rule.conditions.map(renderCondition),
    ...rule.actions.map(renderAction),
    ...(rule.continue ? ["Continue"] : [])
  ].map((line) => `\t${line}`);
  return [header, ...body].join("\n");
}

export function renderHeader(author: string, strictness: string, style: string, version: string): string {
  return [
    "#===============================================================================================================",
    "# 台服 PoE2 過濾器製造機 - Path of Exile 2",
    "#===============================================================================================================",
    `# VERSION:  ${version}`,
    `# TYPE:     2-${strictness.toUpperCase()}`,
    `# STYLE:    ${style.toUpperCase()}`,
    `# AUTHOR:   ${author}`,
    "# BUILDNOTES: Filter generated by Taiwan PoE2 Filter Maker. Syntax baseline: FilterBlade PoE2 Semi-Strict.",
    "#",
    "#------------------------------------",
    "# INSTALLATION / UPDATE :",
    "#------------------------------------",
    "# 1) Paste this file into the following folder: %userprofile%/Documents/My Games/Path of Exile 2/",
    "# 2) INGAME: Escape -> Options -> UI -> Scroll down -> Select the filter from the Dropdown box",
    "#",
    "# UI language uses Traditional Chinese. Filter syntax keeps English Class/BaseType names for game compatibility.",
    ""
  ].join("\n");
}

export function renderTableOfContents(sections: FilterSection[]): string {
  return [
    "#===============================================================================================================",
    "# [WELCOME] TABLE OF CONTENTS + QUICKJUMP TABLE",
    "#===============================================================================================================",
    ...sections.map((section) => `# [[${section.code}]] ${section.title}`),
    ""
  ].join("\n");
}

export function renderSection(section: FilterSection): string {
  const rules = section.rules.map(renderRule).filter(Boolean).join("\n\n");
  return [
    "#===============================================================================================================",
    `# [[${section.code}]] ${section.title}`,
    "#===============================================================================================================",
    section.waypoint ? `# !! Waypoint ${section.waypoint} : "${section.title}" : "${section.titleTw}"` : "",
    "",
    rules
  ].filter((line, index) => line !== "" || index > 2).join("\n");
}

export function generateFilter(sections: FilterSection[], options: { author: string; strictness: string; style: string; version: string }): string {
  return [
    renderHeader(options.author, options.strictness, options.style, options.version),
    renderTableOfContents(sections),
    ...sections.map(renderSection),
    ""
  ].join("\n");
}

function valueForItem(item: SimulationItem, keyword: string): string | number | boolean | undefined {
  const map: Record<string, keyof SimulationItem> = {
    BaseType: "baseType",
    Class: "itemClass",
    Rarity: "rarity",
    AreaLevel: "areaLevel",
    ItemLevel: "itemLevel",
    DropLevel: "dropLevel",
    StackSize: "stackSize",
    Quality: "quality",
    Sockets: "sockets",
    GemLevel: "gemLevel",
    WaystoneTier: "waystoneTier",
    UnidentifiedItemTier: "unidentifiedItemTier",
    Corrupted: "corrupted",
    Mirrored: "mirrored",
    Identified: "identified",
    Width: "width",
    Height: "height"
  };
  const key = map[keyword];
  return key ? item[key] : undefined;
}

export function conditionMatches(condition: RuleCondition, item: SimulationItem): boolean {
  const itemValue = valueForItem(item, condition.keyword);
  if ("values" in condition) {
    const values = condition.values;
    let matched = false;
    if (condition.keyword === "BaseType") matched = values.includes(item.baseType);
    else if (condition.keyword === "Class") matched = values.includes(item.itemClass);
    else if (condition.keyword === "Rarity") matched = item.rarity ? values.includes(item.rarity) : false;
    else matched = values.some((value) => String(itemValue ?? "").includes(value));
    return "operator" in condition && condition.operator === "!=" ? !matched : matched;
  }
  if (typeof condition.value === "boolean") {
    return Boolean(itemValue) === condition.value;
  }
  if (typeof itemValue !== "number") return false;
  switch (condition.operator) {
    case ">=":
      return itemValue >= condition.value;
    case "<=":
      return itemValue <= condition.value;
    case ">":
      return itemValue > condition.value;
    case "<":
      return itemValue < condition.value;
    case "=":
      return itemValue === condition.value;
  }
}

export interface SimulationResult {
  matchedRules: FilterRule[];
  finalRule?: FilterRule;
  hidden: boolean;
  rendered: string;
}

export function simulateItem(sections: FilterSection[], item: SimulationItem): SimulationResult {
  const allRules = sections.flatMap((section) => section.rules).filter((rule) => rule.enabled);
  const matchedRules: FilterRule[] = [];

  for (const rule of allRules) {
    const matches = rule.conditions.every((condition) => conditionMatches(condition, item));
    if (!matches) continue;
    matchedRules.push(rule);
    if (!rule.continue) {
      return {
        matchedRules,
        finalRule: rule,
        hidden: rule.directive === "Hide",
        rendered: renderRule(rule)
      };
    }
  }

  const finalRule = matchedRules[matchedRules.length - 1];
  return {
    matchedRules,
    finalRule,
    hidden: finalRule?.directive === "Hide",
    rendered: finalRule ? renderRule(finalRule) : ""
  };
}

export function validateFilterSyntax(filterText: string) {
  const requiredTokens = [
    "Show",
    "Hide",
    "Continue",
    "Class",
    "BaseType",
    "Rarity",
    "SetFontSize",
    "SetTextColor",
    "SetBorderColor",
    "SetBackgroundColor",
    "PlayAlertSound",
    "PlayEffect",
    "MinimapIcon",
    "DisableDropSound",
    "DropLevel"
  ];
  return requiredTokens.map((token) => ({
    token,
    present: filterText.includes(token)
  }));
}
